"""empty message

Revision ID: 2baaa465d365
Revises: 061172fec244
Create Date: 2024-03-30 17:19:34.405378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2baaa465d365'
down_revision = '061172fec244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comments')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('reviews')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reviews', sa.VARCHAR(length=450), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('books_user_id_fkey', 'user', ['user_id'], ['id'])

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('num_likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_dislikes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='comments_pkey'),
    sa.UniqueConstraint('date', name='comments_date_key')
    )
    op.drop_table('review')
    # ### end Alembic commands ###
